# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ce77f999b1bee65568bf9628af7746580fe4405c5a1c47eaabd9e456af3fb94dbc51fe5fa57dcf7c013f525c03969bc761e11881a0d548b41f2cafca6b4c178e

test:
  secret_key_base: 96a44c32b54da62d4582d4a7c10c8cabc6aff58eed01228fd586fa3d75d5d973ba1ec761f88ff6a7c2bc6654980cd72ebf3cc517a055c1f28281f355ca7bb2fb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
